name: Production deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          yarn
          gulp build-prod

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: 'dist/'
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: berry
          TARGET: public_html/bootstrap/free
          EXCLUDE: '/node_modules/'
